### ISSUE TITLE
出力ファイルの製品名とコンマ、コンマと数量の間に不要な空白が入っている

### ISSUE THREAD

**Issue by TakamasaSugiura** [kwakahara/study_making_201411#27]
出力はCSV形式のファイルですので、空白を入れてはいけません。
現在のプログラムの出力ファイル(例)

```
小倉百人一首 , 3
いぬぼうかるた , 5
```

@2cc7f50

**Comment by mtakahashi-kts** [comment]
確認しました。
masterへマージ後、このissueをcloseしてください。

**Comment by TakamasaSugiura** [comment]
こちらでも動作確認しました。
以下、エビデンス。
![screenshot from 2015-02-19 20 16 31](https://cloud.githubusercontent.com/assets/7827645/6265692/3e15e252-b874-11e4-907d-2f49c318c08e.png)
@872a175
