### ISSUE TITLE
読み込みファイルの読み込み順が規則に合っていない

### ISSUE THREAD

**Issue by TakamasaSugiura** [kwakahara/study_making_201411#29]
第一条件はアルファベット順
第二条件はAscii順(大文字先)であるため、
aBc, Abc, abe, abC(orderと.txtは省略)
のファイルがある場合、
Abc, aBc, abC, abeの順に読まれるのが正解。
しかし、最後にabCが読まれているようです。
※実行結果やソースコードを確認するに、読み込み順の設定が無いのでは？

@2cc7f50

**Comment by mtakahashi-kts** [comment]
#16 と関連

**Comment by mtakahashi-kts** [comment]
Fileの配列をListに詰め替えてCollections#sortしていますが、
Arrays#sortでCollections#sortと同様に配列をソートできます

**Comment by mtakahashi-kts** [comment]
確認しました。
masterへマージ後、このissueをcloseしてください。
