### ISSUE TITLE
「order*.txt」という名前のフォルダがあるとエラーになる

### ISSUE THREAD

**Issue by TakamasaSugiura** [kwakahara/study_making_201411#30]
フォルダはファイルではないので、処理してはいけません。

@2cc7f50

**Comment by mtakahashi-kts** [comment]
「order*.txt」という名前のフォルダがある場合の正しい動作を出題者に確認してください
（その結果を教えてください）
- 該当フォルダを無視
- 受注情報ファイル入力エラー
- その他？

**Comment by kwakahara** [comment]
出題者への確認をとり忘れていました。申し訳ありません。
明日、確認した後に提出いたします。

**Comment by kwakahara** [comment]
出題者へ確認をしたところ、「仕様にかかれていない場合は特にエラー処理をする必要は無く、無視してください。」とのことでした。
現状、このように実装しておりますので確認をお願いします。

**Comment by mtakahashi-kts** [comment]
@fa2a1080e62678ca9a174e9c0792d6b176776f86
確認しました。
masterへマージ後、このissueをcloseしてください。
